##############################
## Build COMPOSER container ##
##############################
FROM composer:2

ARG USER
ARG GID
ARG UID

RUN addgroup --gid ${GID} ${USER}
RUN adduser \
  --ingroup ${USER} \ 
  --gecos ${USER} \
  --uid ${UID} \
  --shell /bin/sh \
  --disabled-password ${USER}

WORKDIR /var/www/html

USER ${USER}