##############################
## Build COMPOSER container ##
##############################
FROM php:8-cli-alpine

ARG USER
ARG GID
ARG UID

RUN addgroup --gid ${GID} ${USER}
RUN adduser \
  --ingroup ${USER} \ 
  --gecos ${USER} \
  --uid ${UID} \
  --shell /bin/sh \
  --disabled-password ${USER}

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

USER ${USER}