version: '3.3'
services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile.nginx
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
      - .docker/nginx/http.d/:/etc/nginx/http.d
      - .docker/nginx/nginx.conf/:/etc/nginx/nginx.conf
    depends_on:
      - builder
      - php
      - postgres
      - supervisor
    networks:
      - api_network
  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      args: 
        GUID: 1000
        USER: laravel
    container_name: php
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - .docker/php:/etc/php7
    working_dir: /var/www/html
    tty: true
    expose:
      - "9000"
    networks:
      - api_network
    depends_on:
      - builder
      - postgres
  supervisor:
    build:
      context: .
      dockerfile: .docker/supervisor/Dockerfile.supervisor
    volumes:
        - ./storage:/var/www/html/storage
    networks:
      - api_network
    depends_on:
      - builder
    env_file:
      - .env
  postgres:
    image: postgres:13.3-alpine3.13
    restart: always
    environment:
      - POSTGRES_USER=countries_api
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=countries_api_database
    ports:
      - "5432:5432"
    # volumes:
    # - .docker/postgresql/data:/var/lib/postgresql/data
    networks:
      - api_network
  builder:
    build:
      context: .
      dockerfile: .docker/utilities/Dockerfile.builder
    image: builder
    container_name: builder
    networks:
      - api_network
  composer:
    image: composer:2
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - api_network
  artisan:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      args: 
        GUID: 1000
        USER: laravel
    container_name: artisan
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - api_network
  npm:
    image: node:14-alpine3.13
    volumes:
        - .:/app
    working_dir: /app
    entrypoint: ["npm"]
  test:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      args: 
        GUID: 1000
        USER: laravel
    container_name: artisan
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/vendor/bin/phpunit']
    networks:
      - api_network
# Docker Networks
networks:
  api_network:
    driver: bridge
