version: '3.9'
services:
  nginx:
    image: nginx:1.23.1-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - .docker/nginx/http.d/default.dev.conf:/etc/nginx/http.d/default.dev.conf
      - .docker/nginx/nginx.conf/:/etc/nginx/nginx.conf
    depends_on:
      - app
      - db
    networks:
      - api_network
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      args: 
        GID: ${GID}
        UID: ${UID}
        USER: ${USER}
    container_name: app
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - .docker/app/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - .docker/app/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - .docker/app/php/php.ini-production:/usr/local/etc/php/php.ini-production
      - .docker/app/php/php.ini-development:/usr/local/etc/php/php.ini-development
    working_dir: /var/www/html
    expose:
      - "9000"
    networks:
      - api_network
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine3.13
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    # volumes:
    # - .docker/postgresql/data:/var/lib/postgresql/data
    networks:
      - api_network
  composer:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      args: 
        GID: ${GID}
        UID: ${UID}
        USER: ${USER}
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['composer']
    networks:
      - api_network
  artisan:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      args: 
        GID: ${GID}
        UID: ${UID}
        USER: ${USER}
    container_name: artisan
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - api_network
  npm:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      args: 
        GID: ${GID}
        UID: ${UID}
        USER: ${USER}
    working_dir: /app
    volumes:
        - .:/app
    entrypoint: ["npm"]
  test:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      args: 
        GID: ${GID}
        UID: ${UID}
        USER: ${USER}
    container_name: artisan
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/vendor/bin/phpunit']
    networks:
      - api_network
# Docker Networks
networks:
  api_network:
    driver: bridge
