############################
## Build NGINX container  ##
############################
FROM nginx:1.21.1-alpine

RUN apk --update add --no-cache

COPY .docker/nginx/http.d/default.prod.conf /etc/nginx/http.d/default.conf
COPY .docker/nginx/nginx.conf /etc/nginx/nginx.conf

COPY . /var/www/html
COPY --from=builder /app/public /var/www/html/public
