############################
## Build NGINX container  ##
############################
FROM nginx:1.21.1-alpine

COPY .docker/nginx/http.d /etc/nginx/http.d
COPY .docker/nginx/nginx.conf /etc/nginx/nginx.conf

WORKDIR /var/www/html/

COPY . .
COPY --from=builder /app/public/dist ./public/dist