#################################
## Build application container ##
#################################
FROM php:8-fpm-alpine3.13

LABEL maintainer="Nizar El Berjawi <nizarberjawi12@gmail.com>"

ARG USER
ARG GID
ARG UID

WORKDIR /var/www/html/

RUN echo "UTC" > /etc/timezone
RUN apk add --no-cache \
    vim \
    git \
    zip \
    curl \
    unzip \
    libzip-dev \
    postgresql-dev && \
  docker-php-ext-install \
    pdo \
    pgsql \
    pdo_pgsql \
    zip

RUN addgroup --gid ${GID} ${USER}
RUN adduser \
  --ingroup ${USER} \ 
  --gecos ${USER} \
  --uid ${UID} \
  --shell /bin/sh \
  --disabled-password ${USER}

RUN chown -R ${USER}:${USER} .

EXPOSE 9000

CMD ["php-fpm"]

USER ${USER}