#################################
## Build development container ##
#################################
FROM php:8.2-fpm-alpine3.18

LABEL maintainer="Nizar El Berjawi <nizarberjawi12@gmail.com>"

ARG USER
ARG GID
ARG UID

WORKDIR /var/www/html/

RUN echo "UTC" > /etc/timezone
RUN apk add --no-cache \
    vim \
    git \
    zip \
    npm \
    curl \
    unzip \
    nodejs \
    libzip-dev \
    postgresql-dev && \
  docker-php-ext-install \
    pdo \
    pgsql \
    pdo_pgsql \
    zip

RUN addgroup --gid ${GID} ${USER}
RUN adduser \
  --ingroup ${USER} \ 
  --gecos ${USER} \
  --uid ${UID} \
  --shell /bin/sh \
  --disabled-password ${USER}

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY --from=stripe/stripe-cli:latest /bin/stripe /usr/bin/stripe

EXPOSE 9000

CMD ["php-fpm"]

USER ${USER}