#################################
## Build application container ##
#################################
FROM php:8.1.11-fpm-alpine3.16

LABEL maintainer="Nizar El Berjawi <nizarberjawi12@gmail.com>"

ARG USER
ARG GID
ARG UID

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 16.8.0

WORKDIR /var/www/html/

RUN echo "UTC" > /etc/timezone
RUN apk add --no-cache \
    vim \
    git \
    zip \
    npm \
    curl \
    unzip \
    nodejs \
    libzip-dev \
    postgresql-dev && \
  docker-php-ext-install \
    pdo \
    pgsql \
    pdo_pgsql \
    zip

RUN addgroup --gid ${GID} ${USER}
RUN adduser \
  --ingroup ${USER} \ 
  --gecos ${USER} \
  --uid ${UID} \
  --shell /bin/sh \
  --disabled-password ${USER}

RUN chown -R ${USER}:${USER} .

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

EXPOSE 9000

CMD ["php-fpm"]

USER ${USER}